version: "2"
services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=open-heroes
      - MYSQL_ROOT_PASSWORD=test
      # - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"